---
title: "LPModel"
output: pdf_document
---

```{r}
# install.packages("lpSolveAPI")

```
```{r}
library(lpSolveAPI)
```

```{r}
lprec <- make.lp(0,9)
```
```{r}
set.objfn(lprec, c(420, 360,300,420,360,300,420,360,300))
```
```{r}
lp.control(lprec, sense='max')
```

```{r}
add.constraint(lprec, c(1,1,1,0,0,0,0,0,0), "<=", 750)
add.constraint(lprec, c(0,0,0,1,1,1,0,0,0), "<=", 900)
add.constraint(lprec, c(0,0,0,0,0,0,1,1,1), "<=", 450)

```

```{r}
add.constraint(lprec, c(20,15,12,0,0,0,0,0,0), "<=", 13000)
add.constraint(lprec, c(0,0,0,20,15,12,0,0,0), "<=", 12000)
add.constraint(lprec, c(0,0,0,0,0,0,20,15,12), "<=", 5000)
```

```{r}
add.constraint(lprec, c(1,1,1,0,0,0,0,0,0), "<=", 900)
add.constraint(lprec, c(0,0,0,1,1,1,0,0,0), "<=", 1200)
add.constraint(lprec, c(0,0,0,0,0,0,1,1,1), "<=", 750)
```

```{r}
add.constraint(lprec, c(1/750,1/750,1/750,-1/900,-1/900,-1/900,0,0,0), "=", 0)
add.constraint(lprec, c(1/750,1/750,1/750,0,0,0,-1/450,-1/450,-1/450), "=", 0)
```

```{r}
set.bounds(lprec, lower = c(0,0,0,0,0,0,0,0,0), columns = c(1,2,3,4,5,6,7,8,9))
```

```{r}
Rownames <- c("Capacity Plant1", "Capacity Plant2", "Capacity Plant3", "Square Foot Plant 1", "Square Foot Plant2", "Square Foot Plant3", "Sales Plant1", "Sales Plant2", "Sales Plant3", "Percent Cap 1-2", "Percent Cap 1-3")

ColNames <- c("Product 1 Plant 1", "Product 2 Plant 1", "Product 3 Plant 1", "Product 1 Plant 2", "Product 2 Plant 2", "Product 3 Plant 2", "Product 1 Plant 3", "Product 2 Plant 3", "Product 3 Plant 3")
```

```{r}
dimnames(lprec) <- list(Rownames, ColNames)
```

```{r}
lprec
```

```{r}
solve(lprec)
```

```{r}
get.objective(lprec)
get.variables(lprec)
```
#We can see here the various levels of production for each of the 3 products at each of the 3 factories. From Left to Right we have products 1-3 nested with Factories 1 - 3.
